language: node_js

node_js:
  - 10

cache:
  yarn: true
  directories:
  - node_modules

install:
  - yarn

script:
  - yarn build

deploy:
  provider: s3
  bucket: "{{cookiecutter.s3_bucket_frontend}}"
  skip_cleanup: true
  local_dir: build
  acl: public_read
  region: {{cookiecutter.region}}
